### ISSUE TITLE
Compiler Support Routines in LTO

### ISSUE THREAD

**Issue by mysterymath** [mysterymath/clang6502#13]
A library of compiler support routines is required to emit good code for the 6502, since some high level operations require far too much code to be efficiently inlined at point of use.

Since the each platform will have a differing number of ZP registers (and other compiler configuration) these routines should be compiled with the users code. Otherwise, they'd need to reserve their own ZP register region, which is inefficient.

This makes the use of the LTO tool mandatory. The .o files shipped with the compiler will contain the LL bitcode of the libraries, and the LTO tool will merge them with the users application and generate 6502 code for them as a whole. This will automatically strip out any unused library features, which is essential for the 6502.

**Comment by johnwbyrd** [comment]
Could you be more specific about which compiler support routines you are referring to?

And yes, I suspect that your workflow is accurate in the general case.

**Comment by mysterymath** [comment]
This should probably be the sum total of routines that ship with the compiler. Shipping libraries that are already lowered to machine code just probably isn't a good fit for this platform, unless you know ahead of time how many ZP registers will be available on the platform where your code will be deployed. Given that just the C64 could have between 6 and 256 available, depending on what you want to break, that's a hard assumption to meet.

**Comment by mysterymath** [comment]
As for right now, I'm targeting a freestanding version of C, which means mostly no standard library, except a couple core headers like <stdint.h>. We will need every libcall that the compiler is capable of emitting from pure C source: soft float routines, the builtin version of memset for clearing structs, and integer multiplication, division, and modulus from 8 to 64 bits.

**Comment by johnwbyrd** [comment]
Sorry, I thought you might have been referring to some form of compiler intrinsics that I was previously unfamiliar with.  The SDK will probably have an opinion as to which zp registers each platform should use, and it will communicate that opinion to clang.

**Comment by mysterymath** [comment]
That's a good point; various memory configurations should probably be subtargets. For example,  mos-nokernal, mos-c64nobasic, and mos-c64basic would by default use 254, 128, and 6 ZP registers, respectively.

Ideally, this logic would be in the clang binary itself; that's the usual way the "SDK" works for GCC and Clang on POSIX. If you say "clang --target=mos-c64nobasic a.c b.c", the clang driver could build the two object files with -flto, perform a link-time-optimization merge with the bitcode standard library and compler support routines, and generate the machine output with -num-zp-ptrs=64. Then you'd just get an output file right in a.out suitable for disk loading.

**Comment by johnwbyrd** [comment]
That puts a lot of strain on clang to know about every conceivable 6502 target out there.  An SDK, in a game development context, includes all of what you are referring to as support libraries, plus example programs and demos, for the targets in question.  You should take a look into the current complexity of the llvm-mos-sdk build pipeline before deciding that clang should subsume it all...  There is a bunch of required functionality there that clang alone cannot easily understand.

**Comment by johnwbyrd** [comment]
Most relevantly, issues such as loading addresses, memory layouts, number of zero page registers, etc., are made in the SDK at the CMake and at the .s level, so developers can easily override those choices, either for a current platform or to port to a new one.

**Comment by mysterymath** [comment]
Clang can easily be made aware of every target out there. It already support 50+ targets. It'll generate completely different code if you tell it your ARM64 is compiling to an Apple device. Or to Windows. Or Linux. And just because clang provides defaults doesn't mean it's difficult to change them.

The expectation for any C compiler frontend is that the simplest possible invocation, "clang -target=mos6502-c64 main.c", will generate an executable binary that runs main. Since most of our platforms do have blessed executable formats, OSes, and disk loaders, breaking from that convention should require considerable additional justification. It'd be very surprising, at least.

**Comment by mysterymath** [comment]
Closing this issue, as I'm removing ca65 ASM support as a requirement. This issue then becomes relatively trivial, since LLD already supports LTO out-of-the-box. If we just make sure that the SDK and compiler-rt libraries are shipped as bitcode, it should do the right thing here automatically.
