### ISSUE TITLE
LTO utility

### ISSUE THREAD

**Issue by mysterymath** [mysterymath/clang6502#7]
A utility should be created to allow files created with clang -flto to be linked together into a single CA65 ASM file. The natural pipeline performs LTO as part of linking, but it'd be nice to have a way to do LTO codegen that targets an assembly language output file. This would allow clang to produce output that could be incorporated into essentially any runtime environment that can currently be constructed via ca65 and ld65.

**Comment by johnwbyrd** [comment]
The assembly backend itself can be told to generate "generic" assembly code instead of an object file, which should be able to be fed into Your Favorite Assembler if for some reason you don't trust llvm-mc.

**Comment by johnwbyrd** [comment]
Also, do not fall into the Commodore 64 centric trap of assuming that ca65 is a preferred assembler throughout the 6502 universe.  If you were targeting an Atari 2600, you'd be programming in DASM.

**Comment by mysterymath** [comment]
> The assembly backend itself can be told to generate "generic" assembly code instead of an object file, which should be able to be fed into Your Favorite Assembler if for some reason you don't trust llvm-mc.

Sure: the main difference is that this is LTO, if you're operating above the layer of a linker, it has to be a separate tool. It can't be the compiler, since that works C file at a time. We could try to get lld itself to spit out assembly, but that's be a bit weird, since the result wouldn't really be *linked*; no addresses would be assigned, externs may still be present, etc.

That being said, if we wanted to produce ASM code for assemblers that don't themselves have the ability to "link", (i.e., no external symbols, no linker scripts, etc), we'd need to have lld do all this work, then output the fully-resolved ASM file. But I'm not super interested in that at the moment, since it's pretty weird, and the utility is questionable. It'd probably be more useful to have lld be the "linking source of truth" and support more ASM variants, but with a novel extern language in the ASM derived from GCCs. Then you could write ASM modules in whatever variant you had, add some annotations in GCC-asm, and link them all together.

> Also, do not fall into the Commodore 64 centric trap of assuming that ca65 is a preferred assembler throughout the 6502 universe. If you were targeting an Atari 2600, you'd be programming in DASM.

Naturally; the right way to do this is emitting ASM from a complete LLVM model of the instruction set. ca65 is just a natural first target, since the other asm variants cannot really be "linked"; you have to specify hard address directly. xa65 is a notable exception.

**Comment by mysterymath** [comment]
After more thoroughly discussing the object file and linking space with johnwbyrd, I'm now reasonably convinced that we can cover the space as well as or better than ca65 currently does. It shouldn't end up being very difficult for users to create linker scripts for platforms that aren't yet supported, and it also should be fairly easy to upgrad user-contributed linker scripts into ones that ship with the compiler and/or SDK. Accordingly, I'm closing this issue, and removing ca65 ASM generation as a requirement. If we want to integrate with ca65 or other ASM variants in the future, it should probably be through assembler variants in LLVM, leaving lld as the ultimate linker and LTO code generator.
